### PR TITLE
20230221 setup firehose

### LINKED ISSUE #8: setup simple way to get access to firehose
We can initially leverage the firehose API endpoint StreamingFast provides to Ethereum mainnet; this will help for a simplified integrated test scripts

### PR DESCRIPTION
**Pull request by benjaminbollen**
to have a simple and quick access to a firehose instance, for now we can gratefully use the API endpoint provided by StreamingFast

- simple shell file to source the ENV keys to access 
- small paragraph in readme on how to get the API key from StreamingFast
- add example .env.example to indicate where the .env file is expected and with what content

resolves #8

### CODE REVIEW

**Comment by vadim-frolov** [comment]
I had good experience using the all-in-one bash function recommended by [StreamingFast](https://substreams.streamingfast.io/reference-and-specs/authentication). One time setup for all projects, always in the path:
```
export STREAMINGFAST_KEY=server_YOUR_KEY_HERE  
function sftoken {
    export SUBSTREAMS_API_TOKEN=$(curl https://auth.streamingfast.io/v1/auth/issue -s --data-binary '{"api_key":"'$STREAMINGFAST_KEY'"}' | jq -r .token)
    echo "Token set on in SUBSTREAMS_API_TOKEN"
}
```

**Comment by benjaminbollen** [comment]
I saw this function, however, why I would split the private environment variables into a `.env` file is for the same reason `.env` files are a pattern: you don't want to commit your private keys.

It's awkward when committed files in the repo are supposed to have explicit private variables

**Comment by vadim-frolov** [comment]
The function is saved to `~/.bashrc`, not committed. A huge pro for me is that I can activate the variable by just typing `sftoken` from anywhere on the machine.

**Comment by benjaminbollen** [comment]
we should not expect devs to put an API call in their `./bashrc` file; you're always able to do this if you like, but it's outside the concern of how to run this repository.

Let's follow the well-established and well-supported `.env` paradigm

**Review by jorgeantonio21 — APPROVED** [review]

**Pull request merged**
